Repository yaroslav-android/Huddle, pull requests merged in 2020-10, with the labels that each got.

#1 [Git] Fix/ Gitignore idea folder
  .gitignore
  .idea/$CACHE_FILE$
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
Labels: :+1: Available for merge

#2 [Git] Feature/ Create PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :+1: Available for merge

#4 [Gradle] Fix/ Group id for JitPack is wrong
  huddle/build.gradle
Labels: :+1: Available for merge

#3 [Git] Feature/ Add JitPack badge to README
  README.md
Labels: :+1: Available for merge

#5 [Dialog] Feature/ Move content setup logic to Helper class
  huddle/src/main/java/team/uptech/huddle/Huddle.kt
  huddle/src/main/java/team/uptech/huddle/HuddleHelper.kt
  huddle/src/main/java/team/uptech/huddle/builder/ImageBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseDialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/FixedLinkMovementMethod.kt
  huddle/src/main/java/team/uptech/huddle/widget/RestrictedHeightRecyclerView.kt
  huddle/src/main/java/team/uptech/huddle/widget/RestrictedHeightScrollView.kt
Labels: :+1: Available for merge

#7 [Dialog] Feature/ Provide tint color support for ImageView
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  app/src/main/java/team/uptech/demo/huddle/MainActivity.kt
  app/src/main/res/drawable/ic_save_the_planet.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/activity_main.xml
  huddle/src/main/java/team/uptech/huddle/HuddleHelper.kt
  huddle/src/main/java/team/uptech/huddle/builder/ImageBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/res/layout/basic_dialog_layout.xml
Labels: :+1: Available for merge

#9 [Dialog] Feature/ Support dialog shape and color
  huddle/src/main/java/team/uptech/huddle/builder/DefaultBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseDialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
Labels: :+1: Available for merge

#13 [Dialog] Feature/Add font support for views
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  app/src/main/res/font/lato_bold.ttf
  app/src/main/res/font/lato_regular.ttf
  app/src/main/res/font/lato_semibold.ttf
  huddle/src/main/java/team/uptech/huddle/HuddleHelper.kt
  huddle/src/main/java/team/uptech/huddle/builder/DefaultBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/FontBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/AndroidExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
Labels: :+1: Available for merge

#14 Feature/Add ripple color support for action buttons
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  app/src/main/res/values/colors.xml
  huddle/src/main/java/team/uptech/huddle/HuddleHelper.kt
  huddle/src/main/java/team/uptech/huddle/builder/CtaBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
Labels: :+1: Available for merge

#11 [I-10] Fix/ Dialog Save State and dialog is not aligned properly
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  huddle/build.gradle
  huddle/src/main/java/team/uptech/huddle/Huddle.kt
  huddle/src/main/java/team/uptech/huddle/builder/DefaultBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseDialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/model/ContentType.kt
  huddle/src/main/java/team/uptech/huddle/model/CtaMode.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ActivityExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
  huddle/src/main/res/layout/basic_dialog_layout.xml
  huddle/src/main/res/values/dimens.xml
  huddle/src/main/res/values/styles.xml
Labels: :+1: Available for merge

#15 [Dialog Builder] Feature/ Simplify dialog DSL
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  huddle/src/main/java/team/uptech/huddle/builder/Builder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ColorBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ContentBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/CtaBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/DefaultBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/FontBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ImageBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ProgressBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/util/dsl/DialogMarker.kt
  huddle/src/main/java/team/uptech/huddle/util/dsl/ElementMarker.kt
  huddle/src/main/java/team/uptech/huddle/util/dsl/RootMarker.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/IntegerExtensions.kt
Labels: :+1: Available for merge

#16 [Extensions] Fix/ Delete Integer Extensions
  app/src/main/java/team/uptech/demo/huddle/DialogManager.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/IntegerExtensions.kt
Labels: :page_facing_up: Review Needed

#17 [Doc] Feature/ Dialog Documentation
  huddle/src/main/java/team/uptech/huddle/Huddle.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseDialog.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ButtonExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ViewExtensions.kt
Labels: :page_facing_up: Review Needed

#18 [Doc] Feature/ Builders documentation
  huddle/src/main/java/team/uptech/huddle/builder/Builder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ColorBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ContentBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/CtaBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/FontBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ImageBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ProgressBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
Labels: :+1: Available for merge, :baby: Child PR

#12 [Doc] Update/ Adding|Replacing documentation
  huddle/src/main/java/team/uptech/huddle/Huddle.kt
  huddle/src/main/java/team/uptech/huddle/HuddleHelper.kt
  huddle/src/main/java/team/uptech/huddle/builder/Builder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ColorBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ContentBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/CtaBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/FontBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ImageBuilder.kt
  huddle/src/main/java/team/uptech/huddle/builder/ProgressBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseBuilder.kt
  huddle/src/main/java/team/uptech/huddle/core/BaseDialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Dialog.kt
  huddle/src/main/java/team/uptech/huddle/core/parameters/Parameters.kt
  huddle/src/main/java/team/uptech/huddle/model/ContentType.kt
  huddle/src/main/java/team/uptech/huddle/model/CtaMode.kt
  huddle/src/main/java/team/uptech/huddle/util/Constants.kt
  huddle/src/main/java/team/uptech/huddle/util/FixedLinkMovementMethod.kt
  huddle/src/main/java/team/uptech/huddle/util/dsl/DialogMarker.kt
  huddle/src/main/java/team/uptech/huddle/util/dsl/RootMarker.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ButtonExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/FloatExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ImageViewExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/TextViewExtensions.kt
  huddle/src/main/java/team/uptech/huddle/util/extension/ViewExtensions.kt
  huddle/src/main/java/team/uptech/huddle/widget/RestrictedHeightRecyclerView.kt
  huddle/src/main/java/team/uptech/huddle/widget/RestrictedHeightScrollView.kt
Labels: :+1: Available for merge, :older_man: Parent PR
